server:
  port: 8081

security:
  header:
    prefix: "Bearer "
  jwt:
    secret: "crescer-2018-1-java-jwt"
    expiration: 86400000 # 1 dia em milisegundos
  public:
    path: "/public/**"

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: redesocial
    password: redesocial
    driver-class-name: oracle.jdbc.OracleDriver

jackson:
    serialization:
      write-dates-as-timestamps: false
